#!/bin/bash
function check {
    if [ $? -ne 0 ]
    then
	echo -e "\e[91m!!!!!!!!!!!!! ERROR : $1 !!!!!!!!!!!!!\e[0m"
	popd > /dev/null
	exit 1
    fi    
}

function p {
    echo -e "\e[93m**** $@ \e[0m"
}
		   
script_dir=$(dirname $(readlink -f $0))
pushd . > /dev/null

cd $script_dir/..
version="`cat version.txt | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'`"

#clean output dir
p Windows build
rm -r out/win
output_dir="out/win/clojure-cli"

#prepare zlib
p Preparing zlib
wget -nc https://zlib.net/zlib-1.2.11.tar.gz
tar -xf zlib-1.2.11.tar.gz
cd zlib-1.2.11/
# Replace the prefix with our custom one
sed -i.bak "s/PREFIX =/PREFIX = x86_64-w64-mingw32-/g" win32/Makefile.gcc
p make
PREFIXDIR=/usr/x86_64-w64-mingw32 BINARY_PATH=$PREFIXDIR/bin INCLUDE_PATH=$PREFIXDIR/include LIBRARY_PATH=$PREFIXDIR/lib SHARED_MODE=1 make -f win32/Makefile.gcc
check 'ERROR MAKING ZLIB'
cd ..

# compile
p compile
nim -d:release --opt:size c -d:mingw -d:project_version="$version" --passL:"-L$script_dir/../zlib-1.2.11/ -lz -s -w" --passC:"-I$script_dir/../zlib-1.2.11/" -o:clojure.exe src/clojure
check 'COMPILE ERROR'

#compress exe
upx clojure.exe
check 'UPX ERROR'

# package
p Packaging...
mkdir -p $output_dir/libexec
cp clojure-tools/clojure-tools-$version.jar $output_dir/libexec
cp clojure-tools/*.edn $output_dir
cp script/clj.cmd $output_dir
mv clojure.exe $output_dir

# zip
p Zipping...
cd out/win
zip -r clojure-cli-win-$version.zip *
check 'ZIP ERROR'

popd > /dev/null
exit 0
