#!/bin/bash

function check {
    if [ $? -ne 0 ]
    then
	echo -e "\e[91m!!!!!!!!!!!!! ERROR : $1 !!!!!!!!!!!!!\e[0m"
	popd > /dev/null
	exit 1
    fi    
}

function p {
    echo -e "\e[93m**** $@ \e[0m"
}
		   
script_dir=$(dirname $(readlink -f $0))
pushd . > /dev/null
cd $script_dir/..
version="`cat version.txt | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'`"

# download
p Downloading official linux install...
link=https://download.clojure.org/install/clojure-tools-$version.tar.gz
wget -O clojure-tools.tar.gz $link
check 'DOWNLOAD ERROR'

# unzip
p Unpack...
tar xzf clojure-tools.tar.gz
check 'UNPACK ERROR'

#nimble install zip
nimble install zip -y
check 'NIMBLE ERROR INSTALLING ZIP'

popd > /dev/null
exit 0
